/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-12 12:15:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Employee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Employee.WorkingDaysCalculator;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.sql.*;

public final class Employee_005fAttendence_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Employee/../CSS/pieChartCSS.jsp", Long.valueOf(1702286972552L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.DayOfWeek");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("Employee.WorkingDaysCalculator");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Employee Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/f327e1d3d1.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".full-height-sidebar {\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	background-color: #111;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-width {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-wider {\r\n");
      out.write("	min-width: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add CSS to make the right side content scrollable */\r\n");
      out.write(".right-content {\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	height: calc(100vh - 72px); /* Adjust the height as needed */\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("	url(\"https://fonts.googleapis.com/css?family=Poppins:600&display=swap\")\r\n");
      out.write("	;\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Poppins';\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pie_chart_content {\r\n");
      out.write("	height: 110px;\r\n");
      out.write("	background-image:\r\n");
      out.write("		url(\"https://scandionocology.con/wp-content/uploads/2018/12/iStock-673266772.jpg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".overlay {\r\n");
      out.write("	background-color: #09162e5;\r\n");
      out.write("	height: 1100px;\r\n");
      out.write("	padding-top: 200px;\r\n");
      out.write("	padding-bottom: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pie_chart_content .container {\r\n");
      out.write("	background: white;\r\n");
      out.write("	border-radius: 40px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_box h1 {\r\n");
      out.write("	padding: 50px 0px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_box {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	border-bottom-left-radius: 5px;\r\n");
      out.write("	border-top-left-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".count_box {\r\n");
      out.write("	background-color: green;\r\n");
      out.write("	border-bottom-right-radius: 30px;\r\n");
      out.write("	border-top-right-radius: 30px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".total-input {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".coronavirus-input {\r\n");
      out.write("	background-color: pink;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".death-input {\r\n");
      out.write("	background-color: skyblue;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".recovered-input {\r\n");
      out.write("	background-color: orange;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"d-flex flex-column  text-bg-dark  col-lg-2 full-height-sidebar custom-width \">\r\n");
      out.write("			<a href=\"/\"\r\n");
      out.write("				class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none\">\r\n");
      out.write("				<svg class=\"bi pe-none me-2\" width=\"40\" height=\"32\">\r\n");
      out.write("				<use xlink:href=\"#bootstrap\"></use></svg> <span class=\"fs-4\">Employee\r\n");
      out.write("					Department </span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<ul class=\"nav nav-pills flex-column mb-auto container-fluid\">\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"Employee_dashboard.jsp\"\r\n");
      out.write("					class=\"nav-link active\" aria-current=\"page\"> <svg\r\n");
      out.write("							class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#home\"></use></svg> Apply Leave\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				");

				int employeeId = Integer.parseInt(request.getParameter("id"));
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"View_leave_History.jsp?id=");
      out.print(employeeId);
      out.write("\"\r\n");
      out.write("					class=\"nav-link text-white\"> <svg class=\"bi pe-none me-2\"\r\n");
      out.write("							width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#speedometer2\"></use></svg> View My Leave History\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Employee_Attendance.jsp?id=");
      out.print(employeeId);
      out.write("\"\r\n");
      out.write("					class=\"nav-link text-white\"> <svg class=\"bi pe-none me-2\"\r\n");
      out.write("							width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#speedometer2\"></use></svg>Attendance\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<!--  <li><a href=\"Departments.jsp\" class=\"nav-link text-white\">\r\n");
      out.write("						<svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#table\"></use></svg> Department Section\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"Leave_type.jsp\" class=\"nav-link text-white\"> <svg\r\n");
      out.write("							class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#grid\"></use></svg> Leave Types\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\" class=\"nav-link text-white\"> <svg\r\n");
      out.write("							class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#people-circle\"></use></svg> Manage Leaves\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"\" class=\"nav-link text-white\"> <svg\r\n");
      out.write("							class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#people-circle\"></use></svg> Manage Admin\r\n");
      out.write("				</a></li> -->\r\n");
      out.write("			</ul>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<a href=\"#\"\r\n");
      out.write("					class=\"d-flex align-items-center text-white text-decoration-none dropdown-toggle\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <img\r\n");
      out.write("					src=\"https://github.com/mdo.png\" alt=\"\" width=\"32\" height=\"32\"\r\n");
      out.write("					class=\"rounded-circle me-2\"> <strong>mdo</strong>\r\n");
      out.write("				</a>\r\n");
      out.write("				<ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\">\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#\">New project...</a></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#\">Settings</a></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#\">Profile</a></li>\r\n");
      out.write("					<li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#\">Sign out</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container col-lg-9 bg-light mt-4 right-content\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"card-body\">\r\n");
      out.write("				<nav class=\"navbar navbar-light bg-light\">\r\n");
      out.write("					<div class=\"container-fluid\">\r\n");
      out.write("						<a class=\"navbar-brand\" href=\"#\"><h4>Employee Section</h4></a> <a\r\n");
      out.write("							class=\"navbar-brand\" href=\"#\">Employee /Attendance System</a>\r\n");
      out.write("						<!-- 	<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("							style=\"hight: 200px; width: 200px\">Admin</button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"dropdown nav-item \">\r\n");
      out.write("							<a class=\"btn btn-primary dropdown-toggle btn-lg  btn-wider \"\r\n");
      out.write("								href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\">User</a>\r\n");
      out.write("							<ul class=\"dropdown-menu\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">Log-Out</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- ========================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<section class=\"pie_chart_content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-3\">\r\n");
      out.write("								<form action=\"../punchIN\" method=\"post\"\r\n");
      out.write("									onsubmit=\"generateUniqueCode()\">\r\n");
      out.write("									<!-- Hidden input field for employee ID -->\r\n");
      out.write("									<input type=\"hidden\" name=\"employeeId\" value=\"");
      out.print(employeeId);
      out.write("\">\r\n");
      out.write("									<input type=\"hidden\" id=\"uniqueCode\" name=\"uniqueCode\" value=\"\">\r\n");
      out.write("									<!-- Hidden input field for punchIN value -->\r\n");
      out.write("									<input type=\"hidden\" name=\"punchType\" value=\"punchIN\">\r\n");
      out.write("									<!-- Submit button -->\r\n");
      out.write("									<button type=\"submit\" id=\"btnPunchIn\"\r\n");
      out.write("										class=\"btn btn-primary dropdown-toggle btn-lg btn-wider\">Check\r\n");
      out.write("										IN</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-9 d-flex justify-content-end\">\r\n");
      out.write("								<form action=\"../punchOUT\" method=\"post\">\r\n");
      out.write("									<!-- Hidden input field for employee ID -->\r\n");
      out.write("									<input type=\"hidden\" name=\"employeeId\" value=\"");
      out.print(employeeId);
      out.write("\">\r\n");
      out.write("									<!-- Hidden input field for punchOUT value -->\r\n");
      out.write("									<input type=\"hidden\" name=\"punchOUT\" value=\"punchOUT\">\r\n");
      out.write("									<!-- Submit button -->\r\n");
      out.write("									<button type=\"submit\"\r\n");
      out.write("										class=\"btn btn-danger dropdown-toggle btn-lg btn-wider\">Check\r\n");
      out.write("										OUT</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- total days  start-->\r\n");
      out.write("						");

						System.out.println(" total days  start");
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");

						String startDate = null;
						String endDate = null;
						int present = 0;
						int absent = 0;

						try {
							Class.forName("com.mysql.cj.jdbc.Driver");
							Connection conn = DriverManager
							.getConnection("jdbc:mysql://localhost:3306/employee_management?user=root&password=root123@");
							PreparedStatement pstmt = conn.prepareStatement(
							"SELECT Joining_Date, CURDATE() as 'current_date' FROM employee_management.add_employee WHERE id=?");
							pstmt.setInt(1, employeeId);

							ResultSet rs = pstmt.executeQuery();
							if (rs.next()) {
								System.out.println("Joining date: " + rs.getString("Joining_Date"));
								System.out.println("Current Date: " + rs.getString("current_date"));

								startDate = rs.getString("Joining_Date");
								endDate = rs.getString("current_date");

								PreparedStatement checkInStatusStateSment = conn.prepareStatement(
								"Select count(*) as total from employee_management.employee_attendance where PunchIN_Time is not null and PunchOut_Time is not null and Employee_Id=?");
								checkInStatusStateSment.setInt(1, employeeId);

								ResultSet resultSet = checkInStatusStateSment.executeQuery();

								// Update the session attribute with the retrieved check-in status
								if (resultSet.next()) {
							present = resultSet.getInt("total");

								}

								else {

								}

							}
						} catch (Exception e) {
							e.printStackTrace();
						}

						WorkingDaysCalculator calculate = new WorkingDaysCalculator();
						long result = calculate.calculateWorkingDays(startDate, endDate);

						absent = (int) (result - present);
						System.out.println("Number of working days between " + startDate + " and " + endDate + ": " + result);
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");

						System.out.println(" total days  end");
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- total days  end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row mt-5 text-center justify-content-center\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<div class=\"main_box\">\r\n");
      out.write("\r\n");
      out.write("									<canvas id=\"mychart\"></canvas>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<div class=\"count_box bg-primary\"\r\n");
      out.write("									style=\"margin-top: 50px; height: 240px;\">\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label for=\"coronavirus-input text-white\">Total Days\r\n");
      out.write("											of Employment</label> <input type=\"text\" value=\"");
      out.print(result);
      out.write("\"\r\n");
      out.write("											class=\"total-input form-control\"  readonly id=\"coronavirus-input\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label for=\"coronavirus-input\">Active Days Present</label> <input\r\n");
      out.write("											type=\"text\" value=\"");
      out.print(present);
      out.write("\" name=\"coronavirus-input\"\r\n");
      out.write("											class=\"coronavirus-input form-control\"  readonly id=\"Present_Days\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label for=\"death-input\">Absent Days</label> <input\r\n");
      out.write("											type=\"text\" value=\"");
      out.print(absent);
      out.write("\" name=\"death-input\"\r\n");
      out.write("											class=\"death-input form-control \" readonly id=\"Absent_Days\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- <div class=\"form-group\">\r\n");
      out.write("										<label for=\"recovered-input\">Recovered</label> <input\r\n");
      out.write("											type=\"text\" name=\"recovered-input\" value=\"1234\"\r\n");
      out.write("											class=\"recovered-input form-control\" id=\"recovered-input\">\r\n");
      out.write("									</div> -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- pie Chat start -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("        const cases = document.getElementById('Present_Days');\r\n");
      out.write("        const deaths = document.getElementById('Absent_Days');\r\n");
      out.write("        const recovered = document.getElementById('recovered-input');\r\n");
      out.write("        const totalDaysInput = document.getElementById('coronavirus-input');\r\n");
      out.write("        const ctx = document.getElementById('mychart').getContext('2d');\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        const presentDays = ");
      out.print( present );
      out.write(";\r\n");
      out.write("        const absentDays = ");
      out.print( absent );
      out.write(";\r\n");
      out.write("        \r\n");
      out.write("        let mychart = new Chart(ctx, {\r\n");
      out.write("            type: 'pie',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: ['Present Days', 'Absent Days'],\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Number of cases',\r\n");
      out.write("                    data: [presentDays, absentDays],\r\n");
      out.write("                    backgroundColor: ['red', 'orange'],\r\n");
      out.write("                    borderWidth: 1\r\n");
      out.write("                }]\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--pie chart end   -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function generateUniqueCode() {\r\n");
      out.write("			// Use a combination of a 4-digit random number and \"AFKIS\" to generate a unique code\r\n");
      out.write("			var randomPrefix = Math.floor(1000 + Math.random() * 9000); // 4-digit random number\r\n");
      out.write("			var uniqueCode = \"AFKIS\" + randomPrefix;\r\n");
      out.write("\r\n");
      out.write("			// Set the generated unique code to the hidden input field\r\n");
      out.write("			document.getElementById(\"uniqueCode\").value = uniqueCode;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		google.charts.load('current', {\r\n");
      out.write("			'packages' : [ 'corechart' ]\r\n");
      out.write("		});\r\n");
      out.write("		google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("\r\n");
      out.write("		function drawChart() {\r\n");
      out.write("			var data = google.visualization.arrayToDataTable([\r\n");
      out.write("					[ 'Status', 'Count' ], [ 'Present', 1 ], [ 'Absent', 4 ] ]);\r\n");
      out.write("\r\n");
      out.write("			var options = {\r\n");
      out.write("				title : 'Attendance Chart'\r\n");
      out.write("			};\r\n");
      out.write("\r\n");
      out.write("			var chart = new google.visualization.PieChart(document\r\n");
      out.write("					.getElementById('piechart'));\r\n");
      out.write("\r\n");
      out.write("			chart.draw(data, options);\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
