/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-23 05:24:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class include_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div\r\n");
      out.write("			class=\"d-flex flex-column  text-bg-dark  col-lg-2 full-height-sidebar custom-width  \">\r\n");
      out.write("			<a href=\"Admin_dashboard.jsp\"\r\n");
      out.write("				class=\"d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none\">\r\n");
      out.write("				<svg class=\"bi pe-none me-2\" width=\"40\" height=\"32\">\r\n");
      out.write("				<use xlink:href=\"#bootstrap\"></use></svg> <span class=\"fs-4\">Employeee\r\n");
      out.write("					Department </span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<ul class=\"nav nav-pills flex-column mb-auto container-fluid\">\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"Admin_dashboard.jsp\" class=\"nav-link active\"\r\n");
      out.write("					aria-current=\"page\"> <svg class=\"bi pe-none me-2\" width=\"16\"\r\n");
      out.write("							height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#home\"></use></svg> Dashboard\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"Employee_Section.jsp\" class=\"nav-link text-white\">\r\n");
      out.write("						<svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#speedometer2\"></use></svg> Employee Section\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"Departments.jsp\" class=\"nav-link text-white\">\r\n");
      out.write("						<svg class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#table\"></use></svg> Department Section\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"Leave_type.jsp\" class=\"nav-link text-white\"> <svg\r\n");
      out.write("							class=\"bi pe-none me-2\" width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#grid\"></use></svg> Leave Types\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li><a href=\"Employee_Attendance_Admin.jsp\"\r\n");
      out.write("					class=\"nav-link text-white\"> <svg class=\"bi pe-none me-2\"\r\n");
      out.write("							width=\"16\" height=\"16\">\r\n");
      out.write("						<use xlink:href=\"#speedometer2\"></use></svg> Employee Attendance\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<!-- manage leave Drop-down end -->\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"Manage_Admin.jsp\"\r\n");
      out.write("					class=\"nav-link text-white\"> <svg class=\"bi pe-none me-2\"\r\n");
      out.write("							width=\"16\" height=\"16\">\r\n");
      out.write("                        <use xlink:href=\"#people-circle\"></use>\r\n");
      out.write("                    </svg> Manage Admin\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<button class=\"btn btn-toggle rounded border-0 collapsed\"\r\n");
      out.write("						data-bs-toggle=\"collapse\" data-bs-target=\"#manageLeaveCollapse\"\r\n");
      out.write("						aria-expanded=\"false\" style=\"margin-left: 30px;\">Manage\r\n");
      out.write("						Leave</button>\r\n");
      out.write("					<div class=\"collapse \" id=\"manageLeaveCollapse\">\r\n");
      out.write("						<div class=\"row text-center\">\r\n");
      out.write("							<ul class=\"nav nav-pills flex-column mb-auto container-fluid\">\r\n");
      out.write("								<li><a href=\"Approved.jsp\"\r\n");
      out.write("									class=\"link-body-emphasis d-inline-flex text-decoration-none rounded text-white\"\r\n");
      out.write("									style=\"margin-left: 17px;\">Approved</a> <i\r\n");
      out.write("									class=\"fa-solid fa-check\" style=\"\"></i></li>\r\n");
      out.write("								<li><a href=\"Decline.jsp\"\r\n");
      out.write("									class=\"link-body-emphasis d-inline-flex text-decoration-none rounded text-white\">Decline\r\n");
      out.write("								</a> <i class=\"fa-solid fa-circle-xmark\" style=\"\"></i></li>\r\n");
      out.write("								<li><a href=\"Pending.jsp\"\r\n");
      out.write("									class=\"link-body-emphasis d-inline-flex text-decoration-none rounded text-white\">\r\n");
      out.write("										Pending </a><i class=\"fa-solid fa-arrow-rotate-right\" style=\"\"></i></li>\r\n");
      out.write("								<li><a href=\"Leave_Histroy.jsp\"\r\n");
      out.write("									class=\"link-body-emphasis d-inline-flex text-decoration-none rounded text-white\"\r\n");
      out.write("									style=\"margin-left: 55px;\">View Leave History</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("		</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
